### ISSUE TITLE
Add a HISTORY file for tracking version changes

### ISSUE THREAD

**Issue by isaac-io** [speedb-io/speedb#100]
RocksDB has a `HISTORY.md` file, where changes between releases are tracked.

We need to have our own change log file (because our versions are different, and because future rebases will mess up the history).

Rename the RocksDB `HISTORY.md` file to `HISTORY_ROCKSDB.md` and add a new `HISTORY.md` file that we'll use to track our change log in. We probably want to use a similar format (we also want to mention the base RocksDB version for each release, at least for the time being).

**Comment by Guyme** [comment]
@rtpro @bosmatt - Please review.
