### ISSUE TITLE
New memtable issue with huge test.

### ISSUE THREAD

**Issue by erez-speedb** [speedb-io/speedb#112]
Looks like we are getting stales during fillup and take some time to recover.
<img width="1174" alt="Screen Shot 2022-08-04 at 14 57 46" src="https://user-images.githubusercontent.com/106964746/182841623-56e0eb89-f9b3-41c5-ab48-7a4bc3ac37e0.png">

**Comment by erez-speedb** [comment]
The issue originally thought to be with just memtable, seems to be regardless.
<img width="1207" alt="Screen Shot 2022-08-08 at 8 28 16" src="https://user-images.githubusercontent.com/106964746/183345790-2fed811d-a8cd-4071-96c7-86ac93ea317b.png">

**Comment by erez-speedb** [comment]
@isaac-io  can you send me few hash's to test?

**Comment by erez-speedb** [comment]
The degradation started between hash [835bcf8c] good on Jun 28 and [7ce6ac43] bad from July 27

https://admin.speedb.io/performance?items=SiweG4JJOqv9r8Mpe06p&items=IMQC27XueKSwk744su0l&colors=%23F06292&colors=%23BA68C8

**Comment by isaac-io** [comment]
Uh, the graphs seem to show the opposite: https://github.com/speedb-io/speedb/commit/835bcf8c62372d3fe9880c5dff0d29ff70891dc4 seems to be bad, and https://github.com/speedb-io/speedb/commit/7ce6ac43e5e0a080df9f71e3359a26d7452b3cb7 is the good one?

**Comment by erez-speedb** [comment]
The difference is due to 
db_bench: fix SeekRandom and ReadRandomWriteRandom fix both these tests to operate not only on the default cf

Not a bug.
