### ISSUE TITLE
Dynamic pinning: track pinned metadata blocks at the CF level

### ISSUE THREAD

**Issue by isaac-io** [speedb-io/speedb#130]
Currently a Column Family has no way to track how much memory of its metadata blocks is pinned in the block cache. We need to be able to track that per table reader and track it in a way that would allow exporting that information for external entities (such as the DB) to consume.

This requires, first and foremost, for each table reader to know if its metadata blocks (currently only filter and index blocks) are pinned. Currently the filter and index readers are the sole owners of the `CachableEntry` for their [respective](https://github.com/speedb-io/speedb/blob/7281a3038b564ab8d2f7c2a6faddc329fcc670a4/table/block_based/filter_block_reader_common.h#L52) [blocks](https://github.com/speedb-io/speedb/blob/7281a3038b564ab8d2f7c2a6faddc329fcc670a4/table/block_based/index_reader_common.h#L82) and don't allow checking for their cache status, so this needs to be allowed.

Additionally, the CF needs to know this information for each table reader, so the table reader needs to expose the pinned memory size for each metadata block for the CF to query. We only care about the `current` version for each CF, and we want to avoid having to do a table cache lookup for each SST file in the version when that information is queried from the CF, so we need to come up with some lightweight way to track that information that would update when changes are done rather than having to actively poll for the state every time (something similar to how the [WriteBufferManager](https://github.com/speedb-io/speedb/blob/7281a3038b564ab8d2f7c2a6faddc329fcc670a4/include/rocksdb/write_buffer_manager.h) gets allocation information through [AllocTracker](https://github.com/speedb-io/speedb/blob/7281a3038b564ab8d2f7c2a6faddc329fcc670a4/memory/allocator.h#L33) hooks [in the MemTable class](https://github.com/speedb-io/speedb/blob/7281a3038b564ab8d2f7c2a6faddc329fcc670a4/db/memtable.h#L516) might be a solution, but there may be better ones).

Lastly, we want the CF to expose this information, broken down by level and metadata block type so that further down the road the DB would be able to query the information and take action.

**Comment by Guyme** [comment]
took a different approach, will be handled in Clean memory manager
