### ISSUE TITLE
Import shorten memtable switch latency

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/speedb#14]
improve memtable switch latency with memtables that require large upfront allocation, such as as the hash-table-based memtable

**Comment by hilikspdb** [comment]
I have reviewed the code. The code now will perform pre-allocation only on the memtable that are ready for that ... I am not sure what is the next step ...

**Comment by ayulas** [comment]
review done moving to qa

**Comment by isaac-io** [comment]
Depends on #98 for testing, since the current implementation only works for the Speedb memtable.

**Comment by Guyme** [comment]
QA passed on https://github.com/speedb-io/speedb/commit/63ee520058f53d406a3ac8ec46c673a44df09c38 
#131

**Comment by Yuval-Ariel** [comment]
QA passed on f49d936a36d41f1ef4e4f23bfe24a63dac04654a

**Comment by Yuval-Ariel** [comment]
QA passed on 62b3f64c66f3bfc7d4670d2bf7f85b2d9d46d333

**Comment by erez-speedb** [comment]
Past performance tests on hash  7e5e7bc04bb8813f4bea66dc6030074b4b2658c3


![Image](https://user-images.githubusercontent.com/106964746/201595150-836e042d-6817-4d3c-a54e-7de495f62a8c.png)

**Comment by erez-speedb** [comment]
Also passed QA

**Comment by Guyme** [comment]
Switch functionality was added to ticket #98 PR #188 https://github.com/speedb-io/speedb/commit/7e5e7bc04bb8813f4bea66dc6030074b4b2658c3
