### ISSUE TITLE
README: logos render in a broken manner

### ISSUE THREAD

**Issue by isaac-io** [speedb-io/speedb#149]
After the merge of #135, rendering of the repo page and the readme page is broken on mobile (horizontal scrolling is activated and the logo is partially hidden) due to the heading logo having a fixed width, instead of a relative width with a `max-width`:

![image](https://user-images.githubusercontent.com/81761131/187485085-2e708b98-a01e-48b9-8303-398c82c08de2.png)

Additionally, on desktop with dark mode the logos look bad, and the bee is almost invisible:

![image](https://user-images.githubusercontent.com/81761131/187485318-0a6fae52-657d-4314-b07d-e6eda9330d7f.png)

**Comment by isaac-io** [comment]
> What device and browser are you using?

My screenshot was from Firefox Mobile on a Motorola device, but it seems to render fine now. There seems to have been a change on GitHub's side in the mean time (the image now has `style="max-width: 100%; display: inline-block;"` applied to it), so you can disregard that issue.

**Comment by rtpro** [comment]
Update: awaiting shiny new graphics compatible with Dark Mode.
