### ISSUE TITLE
Paired Block Bloom Filter Algorith - BPK Adjustment to avoid performance degradation with bpk<=10

### ISSUE THREAD

**Issue by udi-speedb** [speedb-io/speedb#161]
During @noamhaham's performance runs, he discovered that there is a performance degradation with the paired filter with bpk=10.
suggests to adjust the user's bpk (round up) to end up in an effective bpk that is larger that the user's. This adjustment implies more memory consumption for the filters (relative to not rounding up). The more keys a filter has, the smaller the adjustment / memory-consumption-increase and vice versa => 
Noam expects this to be felt more in Level 0 and less as the level progresses. However, since most of the data is in the lower levels, he expects the total consumption increase to be negligible.

**Comment by udi-speedb** [comment]
Pull request: https://github.com/speedb-io/speedb/pull/163

**Comment by erez-speedb** [comment]
The 8 BPS test 


![Image](https://user-images.githubusercontent.com/106964746/206268943-b10b35f5-d1c6-4a04-82f8-aa46777c4425.png)

**Comment by erez-speedb** [comment]
Pass performance tests

**Comment by udi-speedb** [comment]
@erez says he has checked a branch named pared_bloom_filter-improved
I will take a look at it now
