### ISSUE TITLE
Change default compaction threads from 1 to 8

### ISSUE THREAD

**Issue by bosmatt** [speedb-io/speedb#169]
Changing the default compaction threads shows performance improvement as can be seen below.
 We believe that even there are not too many cores in the system, the performance is still better with more threads than with a single thread. 

![Image](https://user-images.githubusercontent.com/107058910/191572883-55ed2004-5320-42f7-8a3d-87ac840bee6b.png)

**Comment by erez-speedb** [comment]
@isaac-io  testing is done, please merge

**Comment by isaac-io** [comment]
Thanks! Waiting for Assaf to approve that QA tests passed as well.
