### ISSUE TITLE
makefile: speed up test runs startup time

### ISSUE THREAD

**Issue by isaac-io** [speedb-io/speedb#174]
The Makefile has many places where it needlessly invokes a sub-make instead of declaring the dependencies correctly. This is causing slowdowns on startup, and especially noticeable during test runs (`make check`) where each time a sub-make is invoked it regenerates `make_config.mk` and that takes a long time. Rework the dependency graph so that at least running tests doesn't involve invoking make three times.

**Comment by Yuval-Ariel** [comment]
QA passed
