### ISSUE TITLE
Simple front end to test basic functionality 

### ISSUE THREAD

**Issue by bosmatt** [speedb-io/speedb#227]
Why:
- This software should provide a simple framework for sanity test. 
- Playground for a basic experience with Speedb data engine. 

What:
- Simple front end to test basic functionality 
-The software should support basic functionalities as: open db, close db, put, get, seek, delete, using CLI. 

Who:
Demoing basic functionality, playground

**Comment by Yuval-Ariel** [comment]
the ldb tool offers such capabilities:
https://github.com/facebook/rocksdb/wiki/Administration-and-Data-Access-Tool#ldb-tool 
is that not sufficient?

**Comment by Yuval-Ariel** [comment]
@bosmatt  can we close this?
