### ISSUE TITLE
Upgrade to RocksDB 7.7.3

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/speedb#264]
instead of https://github.com/speedb-io/speedb/pull/219

**Comment by Yuval-Ariel** [comment]
instead of https://github.com/speedb-io/speedb/pull/219

**Comment by erez-speedb** [comment]
Passed performance tests

![Image](https://user-images.githubusercontent.com/106964746/204235492-68ff1236-9313-45d3-8039-3e96c3007c21.png)
![Image](https://user-images.githubusercontent.com/106964746/204235490-cfc95611-759e-4b11-aff8-c2487eecc1f7.png)
![Image](https://user-images.githubusercontent.com/106964746/204235491-f6b7a64b-9d40-40e9-a1bd-cae3e699f5fe.png)
