### ISSUE TITLE
db_bench group option force compression

### ISSUE THREAD

**Issue by erez-speedb** [speedb-io/speedb#282]
Running basic test with the group option, fails on compression:

#~/speedb# /root/speedb/db_bench --groups " --benchmarks=fillrandom,levelstats --compression_type=None -db=/data/ -num=500000 -value_size=1000 -key_size=16 --delayed_write_rate=536870912 -report_interval_seconds=1 -max_write_buffer_number=4 -num_column_families=1 -histogram -report_file=fillrandom.csv --disable_wal=true -max_background_compactions=8 -max_background_flushes=4 -bloom_bits=10 " "--benchmarks=readrandom,levelstats -duration=45 --use_existing_db -report_file=readrandom.csv --disable_wal=false -threads=50"
Set seed to 1669901876925011 because --seed was 0
Initializing database Options from the specified file
Initializing database Options from command-line flags

ERROR: open error: Invalid argument: Compression type Snappy is not linked with the binary.

**Comment by udi-speedb** [comment]
The problem is the '--groups'. It should be '-groups'
I will open a separate enhancement issue to support both
