### ISSUE TITLE
Paired Block Bloom Filter Algorithm

### ISSUE THREAD

**Issue by udi-speedb** [speedb-io/speedb#29]
Why :

Reduce false positives rate while using the same amount of memory.

What:

Develop a filter which is fast and low on CPU consumption on the one hand, but with a better memory footprint- FPR trade-off on the other hand.

Technical detail: 

In the traditional bloom filter there is a tradeoff between memory usage and performance. Rocksdb blocked bloom filter takes less time but consumes extra memory.

Ribbon filter, on the other hand, takes ~30% less memory but is much slower than the bloom filter (factor of 4). 

The idea is to improve bloom filter in both memory consumption and keep it high performant. 

Who:

The proposed filter should be most beneficial when there is a need for a very small FPR. Typically this happens when the penalty of a false positive is very big compared to the filter test time (database on the disk), and when true positives are rare.

Integrate a new type of filter policy: Paired Block Bloom Filter

**Comment by isaac-io** [comment]
Didn't show an improvement with #101, so we need to define a good test to show the value of the feature.

**Comment by erez-speedb** [comment]
Running the test on a single HDD (simulating disk as bottleneck) and with DB size larger than RAM
Showed clear benefit

![Image](https://user-images.githubusercontent.com/106964746/188591289-92971355-0a37-463e-8891-454365e85605.png)

With no additional memory usage, compare to the default bloom with the same BPK

**Comment by isaac-io** [comment]
Depends on #71 and on #123.

**Comment by Yuval-Ariel** [comment]
QA passed on 4cf14cb2ae85e4c6ad906e26c4aa2269578f3716

**Comment by erez-speedb** [comment]
Pass performance tests.

![Image](https://user-images.githubusercontent.com/106964746/197541167-2299106d-c651-4ca9-b91f-2207589ba19e.png)
