### ISSUE TITLE
db_bench: Recreate only dbs that are in actual use in a group of benchmarks

### ISSUE THREAD

**Issue by udi-speedb** [speedb-io/speedb#290]
When a benchmark in a group requires a freshdb (e.g., fillXXX benchmarks), all of the DB-s are recreated.
However, a user may now use the -dbs_to_use flag to have the benchmark operate on a subset of the available db-s. It makes sense (and aligns with the way the -dbs_to_use flag behaves) to also only recreate those db-s rather that all of them.

**Comment by Yuval-Ariel** [comment]
@udi-speedb , have you verified this works as expected? normal QA cycle is useless here since the changes are only in db_bench..

**Comment by udi-speedb** [comment]
@Yuval-Ariel yes I have

**Comment by erez-speedb** [comment]
I prefer to tests this after this https://github.com/speedb-io/speedb/issues/285 is resolved.

**Comment by udi-speedb** [comment]
I have assigned to @Yuval-Ariel to merge
