### ISSUE TITLE
generic switch memtable

### ISSUE THREAD

**Issue by ayulas** [speedb-io/speedb#296]
generic switch memtable allows the ability to pre create memtable that allocated memory as part of the constructor
this will reduce the penelty time of switch mutable memtable which by definition will effect write flow

**Comment by erez-speedb** [comment]
Tests with both HashSpdb and skip_list
No degradation:

**Comment by erez-speedb** [comment]
@Yuval-Ariel  please test

**Comment by ayulas** [comment]
@yuval i ran several times the full CI and also ran the unitest serveral times on my azure instance. all passed.
pls recheck and verify
THANKS!

**Comment by Yuval-Ariel** [comment]
looks fine. whos your reviewer?

**Comment by ayulas** [comment]
isaac did. months ago
already in git and not github ...
