### ISSUE TITLE
Add a complete report of test plan

### ISSUE THREAD

**Issue by giladmaya** [speedb-io/speedb#320]
**Is your feature request related to a problem? Please describe.**
Running the tests is a bit frustrating. When running the tests via 'make test' it seems that the test stops after the first failure; hence we can't tell if additional tests are broken or even how many tests remained in the test plan. 
As a result, contributors will be able to better understand the impact of the change they've made and the overhead of re-running the tests and discovering only one issue at a time will be reduced significantly. 

**Describe the solution you'd like**
I would add an option to run `make test` with `stop-on-first-failure` approach. The default behavior would be to complete the entire test plan.
On both options, the failures would be collected during the run and exported to a text file.

**Comment by Yuval-Ariel** [comment]
running the unit tests in parallel already provides such functionality wither with gnu parallel or ctest if you're using cmake. please refer to https://docs.speedb.dev/documentation/getting-started/how-to-contribute/contribute-code#c++-unit-tests and see if that works out for you. 
also, @AmnonHanuhov , can you elaborate more about the dependencies regarding this issue? #122  and https://github.com/speedb-io/speedb/commit/c528ec8fd1230cbde44a74dce34e267cc650c287

**Comment by Yuval-Ariel** [comment]
also note this issue - https://github.com/speedb-io/speedb/issues/288

**Comment by AmnonHanuhov** [comment]
> running the unit tests in parallel already provides such functionality wither with gnu parallel or ctest if you're using cmake. please refer to https://docs.speedb.dev/documentation/getting-started/how-to-contribute/contribute-code#c++-unit-tests and see if that works out for you.
> also, @AmnonHanuhov , can you elaborate more about the dependencies regarding this issue? #122 and [c528ec8](https://github.com/speedb-io/speedb/commit/c528ec8fd1230cbde44a74dce34e267cc650c287)

Regarding #122 there are no special dependencies when using gtest-parallel for running the tests in parallel, that is, there is no need to install additional python packages and the use of ‘make check’ is exactly the same. 
Currently on the main branch, to run all the tests in parallel and to overcome the issue mentioned by @giladmaya , we execute ‘make check’, which uses GNU Parallel (has to be pre installed on the users machine) to run the tests in parallel. 
After #122 will be merged, to run the tests in parallel you will still only need to execute ‘make check’, which will use gtest-parallel,  but the good thing is gtest-parallel comes bundled in our repo.
