### ISSUE TITLE
db_bench: align the tests we're using

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/speedb#325]
**Describe the bug**
when used with multiple cfs, the test will only use the default cf.

**Additional context**
this has been addressed before but must've slipped during rebasing

**Comment by Yuval-Ariel** [comment]
also fix BGWriter , readrandom, seekrandom and readrandomwriterandom.
made sure these tests:
1. us one rand num to get the db and cf and the key which makes it possible to find a key in a cf later on.
2. report the bytes throughput
3. ability to have a read and write limiter where ever relevant.
4. operations are done on all cfs randomly and not only on the default cf

**Comment by Yuval-Ariel** [comment]
@erez-speedb , plz run performance. we're expecting no change in all tests. the only change that should be visible is in the seekrandomwriterandom which will use all the cfs in huge db test and the seekradomwhilewriting now writes to all cfs

**Comment by Yuval-Ariel** [comment]
@erez-speedb  , status?

**Comment by erez-speedb** [comment]
@Yuval-Ariel  The multi CF is running but I'm not sure what performance is there to test here?

**Comment by Yuval-Ariel** [comment]
its a matter of correctness.. but if theres a performance difference in the single cf tests then its bad

**Comment by erez-speedb** [comment]
Multi CF test,
The difference is only with the seekrandomwriterandom tests
https://admin.speedb.io/performance?items=nl1nwB81l5DDRhuzwWjd&items=hKWqp0Aknv7eR3CDlnnG&colors=%23F06292&colors=%2300796b


![Image](https://user-images.githubusercontent.com/106964746/216367290-49c958e9-961c-45a0-8fb2-29ed877b81e7.png)

**Comment by erez-speedb** [comment]
The small DB showed degradation with the seekrandomwriterandom tests.
Running the test and the large obj test again


![Image](https://user-images.githubusercontent.com/106964746/216806782-96d6ef2d-8e30-4d59-bd27-2f0d6fc5f39d.png)

**Comment by erez-speedb** [comment]
@Yuval-Ariel I tested few times and both large obj and small DB tests shows the degradation 
https://admin.speedb.io/performance?items=IxsAvKvunCafENia4udE&items=DQbr0ntUjYJDz3RLExzO&colors=%23F06292&colors=%23BA68C8
And 
https://admin.speedb.io/performance?items=IxsAvKvunCafENia4udE&items=DQbr0ntUjYJDz3RLExzO&colors=%23F06292&colors=%23BA68C8

This is unless the degradation is from introducing the rate limit, and then it is part of a separate discussion.
For that, I'm testing the old main again.

**Comment by erez-speedb** [comment]
The above degradation is from the rate limit

![Image](https://user-images.githubusercontent.com/106964746/216941408-24cdcf61-b931-4bd5-b1b7-012d8bd9622b.png)

Past performance tests.
