### ISSUE TITLE
Lightweight Statistics

### ISSUE THREAD

**Issue by bosmatt** [speedb-io/speedb#336]
**What**:
We would like to support light weight statistics that will have little to no impact on the performance. 

**Why:**
- Speedb performance can be tracked easily by customers 
- Currently, Rocksdb statistics reduce performance by 20%
- Easy troubleshooting 
- This should be the base line for monitoring graphs 

**Who**: 
- Testing 
-Customers 
-POCs

**Requirements:** 

1. Collecting statistics should not affect performance 
2. Collect statistics once every X operations (x should be a default value that can be changed)
   2.1 The user shall be able to change the default and collect in different frequency 
3. The statistics should be printed to a dedicated stats file: Speedb-stats (file name TBD)
    3.1  It should keep a history of 4 days and then rotate (TBD, depends on file size) 
    3.2  The file size/total duration should be configurable 
4. The counters should be accumulated 
5. The following metrics should be collected: (WIP) 

- Write latency 
- Read latency 
- Table sizes 
- Get 
- Multi get
- User Write (db.write.micros)
- Read
- Compaction related metrics*
- IOs
- BW 
- Writes to the disks (write.raw.block)
- Seek

**Comment by Guyme** [comment]
closed due to research on #255
