### ISSUE TITLE
Live Config Changes

### ISSUE THREAD

**Issue by Guyme** [speedb-io/speedb#337]
**What** 
Provide an interface to change configurable parameters on the fly even if the application does not support it

**Why** 
- Improve user experience when tuning parameters during PoCs, testing and customer environment. 
- Changing parameters without restarting the database 

**Who** 
- Testing
- Customers (production) 
- POCs

**Functional Requirements:** 
- The user should be able to change with this method mutable parameters only. This method cannot be used to change immutable parameters. 
Example: The user shall be able to load a config file, with similar format to the Options file and to call the appropriate rocksdb update option (pending RnD decision) 
- The new option/s should be loaded on the fly without the need to reload/recompile the code. 
- When changing a parameter, the old and new values should be printed to the log

**Comment by Yuval-Ariel** [comment]
we've agreed that using this feature with the stress test requires addition of injecting the "refresh options file". @mrambacher will this be included in this ticket or a subsequent one?
