### ISSUE TITLE
Add index size report per column family

### ISSUE THREAD

**Issue by bosmatt** [speedb-io/speedb#338]
Customer ask

In order to get better understanding of the current resource utilization, the ask is to report the index size per CF to the log.

**Comment by udi-speedb** [comment]
Notes for performance / QA:
The change consists of counting per-cf sizes when collecting block cache statistics.
There is now, per CF, another line in the log when displaying the block cache statistics. The log line displays, per cf, the sizes in the cache of the index blocks, filter blocks, and data blocks.
So, QA should verify that the data displayed in the log is correct (the sum of all sizes of all the cf-s should be the same as the total for the entire block cache).
Performance-wise, I expect that there will not be any noticeable performance degradation.

**Comment by Yuval-Ariel** [comment]
@erez-speedb  plz check

**Comment by erez-speedb** [comment]
I'm running our multi CF test, and will run the small obj test with 2 CF as well

**Comment by erez-speedb** [comment]
@udi-speedb  Can you pls rebase on latest main?
I see some degradation on the small obj test and I'm not sure if it from the test, the code or the main it was based on.

**Comment by udi-speedb** [comment]
@erez-speedb I have rebased my branch on latest origin/main, built, successfully ran "make check" and pushed (forced) the branch.

**Comment by erez-speedb** [comment]
After the second test, there is a degradation with seeks.
https://admin.speedb.io/performance?items=kXAjadycwIiq5RlgGBZp&items=iJeTPOC4ExuK3i0s3RcJ&items=cbAsF4BziNIhcRaxfO4f&colors=%23F06292&colors=%23BA68C8&colors=%2300796b
