### ISSUE TITLE
Global delayed write rate 

### ISSUE THREAD

**Issue by bosmatt** [speedb-io/speedb#346]
What:
Delayed write rate in a system level - shared to all DBs
Why:
The current delayed write mechanism allows the user to set a limit per database. 
Databases that have internal delay may be starved by others that work faster
Therefore a write-control for the entire system is requires. 
Who:
 -This will mostly relevant for systems with multiple DBs. 

Requirements: 
1. The user shall have the ability to set delayed write rate to each DB if wishes or a global rate for all the DBs.
2. At this stage, the triggers to activate the delayed writes should remain the same. 
3. The system should be able to control the writes rate for the entire system
4. As a result, starvation should be prevented and the system write rate can be predicted.

**Comment by erez-speedb** [comment]
Tests are running

**Comment by erez-speedb** [comment]
Small obj possible improvement with seekrandomwriterandom

https://admin.speedb.io/performance?items=mamXAjSCEql4j58i9aFD&items=xR8Qf2MMX1b9Ow3ay03f&items=fnl1xj1oh0NkzlQPW32X&colors=%23F06292&colors=%23BA68C8&colors=%2300796b

large Obj no gain no pain
https://admin.speedb.io/performance?items=4gWhlhTcRlfRzZHVgpdr&items=4YdM3KKBOH1kajHL7xnB&colors=%23F06292&colors=%2300796b

Huge DB no improvement in some tests std is even bigger.

https://admin.speedb.io/performance?items=5xqH5YcIeWrwyiCV7vgC&items=R4RBxn4b5jAQOXUvQMHF&colors=%23F06292&colors=%2300796b

**Comment by erez-speedb** [comment]
@hilikspdb  try ro run with 2 CF, with 90/10 distribution.
Didnt get stalls and didnt get improvments.
`/home/ubuntu/speedb/db_bench --compression_type=None -db=/data/ -num=200000000 -value_size=1000 -key_size=16 --delayed_write_rate=536870912 -report_interval_seconds=1 -max_write_buffer_number=4 -num_column_families=2 -histogram -max_background_compactions=8 -cache_size=8388608 -max_background_flushes=4 -bloom_bits=10 -column_family_distribution=90,10 -duration=900 --use_existing_db -threads=50 -duration=900 -benchmark_read_rate_limit=0 -benchmark_write_rate_limit=0 -report_file=overwrite.csv --benchmarks=overwrite,levelstats`

https://admin.speedb.io/performance?items=cByN7eMAY3xipublUQ9R&items=FF08AyqBUFlqfOE7O3ra&colors=%2300796b&colors=%23BA68C8

We need better definition.

**Comment by hilikspdb** [comment]
1) with 2 disks and relatively small cf and object size=1k the write flow
is the limit. please use either 1 disk or else 2K objects or else larger
database to get into the state where the disks are the bottleneck
2) in naked eye I see a difference when we set data smoothing = 1 or 6
(less jumpy)

**Comment by Yuval-Ariel** [comment]
the test above **fails** to show the benefit of always picking the slowest cf since:
1. distribution is not really 90/10 as can be seen in the sizes of the cfs. size is same at the end of the fillrandom 74/72 Gb. later on it increases to 2-3 times.
2. as hilik mentioned, there needs to be accumulation of compaction debt which cannt happen when the disks are not the bottleneck. it can be seen since the only place where there are WARN stalls is in the fillrandom test.

**Comment by erez-speedb** [comment]
1. the 90/10 do not apply to the fillup stage in the test
2. running the same test again on a single disk

**Comment by erez-speedb** [comment]
@Yuval-Ariel  @hilikspdb  pls review single disk results
https://admin.speedb.io/performance?items=s1w4Mw4iPNEhtS95uMG4&items=yjGL1BIrAuIS1m2bvw8I&colors=%23F06292&colors=%2300796b

**Comment by erez-speedb** [comment]
@Yuval-Ariel  ??

**Comment by Yuval-Ariel** [comment]
@erez-speedb , this test also doesnt show the benefits since the only place where the 2nd cf reaches a delay state is in the fillrandom test which has equal distribution. 
plz run again with 90/10 also in the fillup with level0_slowdown_writes_trigger = 12.

this feature enables the db to use the lowest delay requirement from all cfs and all dbs the wc is connected to. 
the benefit we expect to see in this kind of test is when cf1 needs delay of 100 but then cf2 needs delay of 500 and overrides it so that cf1 is running with a higher rate than it should. but if cf2 is never in a delay state then this is useless.

**Comment by hilikspdb** [comment]
yuval , all the cf(s) in all the db(s) should be in a delay state if one cf
is in a delay state!

**Comment by erez-speedb** [comment]
@Yuval-Ariel per your request 90/10 on all tests.
https://admin.speedb.io/performance?items=uLk6VxCEpOvkLogek1PX&items=O7kvLAMpl37NPg2lMJjY&colors=%23F06292&colors=%2300796b

Still nothing visible.

**Comment by Yuval-Ariel** [comment]
@erez-speedb  yes because the 2nd cf didnt reach more than 4 L0 files.. so it didnt reach a delay state.
try again with 80/20 , 70/30 , 60/40. and with level0_slowdown_writes_trigger = 8. thanks

**Comment by Yuval-Ariel** [comment]
thanks @erez-speedb for your attempts. i'll run the performance

**Comment by Yuval-Ariel** [comment]
red - global delay (5e01ba7055c7f50c59b321d02e99a195af979567) 
green - main (0d43a01c32c20be57e966c070d50d6d6bc85568f)
red is much more stable.
![image](https://user-images.githubusercontent.com/105581454/225282476-917ae329-181f-46e7-9fa0-9ca673df32a5.png)
https://admin.speedb.io/performance?items=zcK83ckPh3HQlox9FkXy&items=zndeb524FsgAQT1LilPX&colors=%23F06292&colors=%232e7d32  

more exactly measured by the standard deviation of the ops/sec:
global - 124973 ( **30%** more stable)
main - 173066 

cmd to reproduce:
db_bench --compression_type=None -db=/data/ -num=200000000 -value_size=1000 -key_size=16 --delayed_write_rate=536870912 -report_interval_seconds=1 -max_write_buffer_number=4 -num_column_families=3 -histogram -max_background_compactions=8 -cache_size=8388608 -max_background_flushes=4 -bloom_bits=10 -benchmark_read_rate_limit=0 -benchmark_write_rate_limit=0 -report_file=fillrandom.csv --disable_wal=true --benchmarks=fillrandom,levelstats --column_family_distribution=50,24,26 --level0_slowdown_writes_trigger=8 -write_buffer_size=268435456

**Comment by Yuval-Ariel** [comment]
@Guyme , ok to merge?

**Comment by Guyme** [comment]
@Yuval-Ariel - YES!
