### ISSUE TITLE
Upgrade base RocksDB version to 7.7.8

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/speedb#357]
we're currently on 7.7.3 and there are only Bug fixes so no reason not to upgrade

**Comment by Yuval-Ariel** [comment]
@udi-speedb  , im having trouble merging commit bbf61996a94d3281a120cef2892d9126b9083a45 which conflicts which changes you introduced in https://github.com/speedb-io/speedb/issues/132 . can you cherry-pick the commit and solve the conflicts on the 357 branch?

**Comment by Yuval-Ariel** [comment]
@erez-speedb  plz check. there should be no degradation

**Comment by erez-speedb** [comment]
No degradation, small DB even shows some improvement.
Small DB 
https://admin.speedb.io/performance?items=OReqh8hUYTtHjg2ev7j8&items=MTnDOa9oyhGa33CyQgci&colors=%23F06292&colors=%2300796b
Small obj
https://admin.speedb.io/performance?items=q70AYGrgS0T1oi8MsaZF&items=zmqpQ9ogatg10p1lqXkC&colors=%23F06292&colors=%2300796b
Large obj
https://admin.speedb.io/performance?items=lT4eb2RvOIOgkQtMA4eN&items=DQbr0ntUjYJDz3RLExzO&colors=%23F06292&colors=%2300796b

**Comment by erez-speedb** [comment]
@Yuval-Ariel if this passed QA pls move it to merge
