### ISSUE TITLE
Dynamic Delay: CFs shouldnt override each other

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/speedb#358]
Currently, in a setting of multiple cfs, the delayed_write_rate_ value is overridden in each call to set_delayed_write_rate. this is a problem that existed also when use_dynamic_delay = false but was much less severe since the new delayed rate is always calced from the old. so in the example below, the 2nd cf would set the rate to about 10 Mb/s instead of 512Mb/s.
e.g. a scenario where there are 2 cfs, L0 slowdown is 20, L0 stop is 36 and delayed_write_rate is set to 512Mb/s. 
cf1 has a serious delay state (35 L0 files) and sets the delayed_write_rate_ to 8Mb/s but right after it sets it, cf2 finishes a flush and sets delayed_write_rate_ to 512Mb/s since it only has 20 L0 files. all further writes will run in speed of 512Mb/s until a new InstallSuperVersion happens which is not what should happen.

what should happen is that system will run at the slowest speed required from all cfs. 

do this by storing the delay requirements of all the CFs in the write controller and only set a new delayed_write_rate_ when its smaller than the min.

**Comment by Yuval-Ariel** [comment]
@erez-speedb  , status?

**Comment by erez-speedb** [comment]
Looking at the multi CF test
https://admin.speedb.io/performance?items=s8zPAKKkA6beO0NwPX5Z&items=hKWqp0Aknv7eR3CDlnnG&colors=%23F06292&colors=%23BA68C8
<img width="1229" alt="Screenshot 2023-02-09 at 11 58 33" src="https://user-images.githubusercontent.com/106964746/217780176-699c0a97-c7a6-4362-acac-b1e857866ca1.png">
There is no obvious improvement is stability of performance.

However, there are no degradation in the rest of the tests 
https://admin.speedb.io/performance?items=1fgedOdqXztBsfrXx7W6&items=VhI3ee0518hcWoQ7nGov&colors=%2300796b&colors=%23BA68C8
https://admin.speedb.io/performance?items=bpNEndqhyW9SLaMmftzM&items=DQbr0ntUjYJDz3RLExzO&colors=%23F06292&colors=%2300796b
https://admin.speedb.io/performance?items=5TW4COdc1Nz81dwYliKx&items=zmqpQ9ogatg10p1lqXkC&colors=%23F06292&colors=%2300796b

@Yuval-Ariel  @Guyme  If this improves correctness then we can merge, performance wise, it dost seems to make a difference
