### ISSUE TITLE
Avoid flooding disk I/O on file purges

### ISSUE THREAD

**Issue by isaac-io** [speedb-io/speedb#36]
With the changes in #5, when we need to purge a large amount of files, or large files which don't have their blocks allocated contiguously, or on bitmap-based filesystems (even when we have a contiguous range of blocks for each file), we may incur a high load on the disk when purging obsolete files that would eat into the bandwidth available to user operations and compactions.

Change the implementation of the default `Env`'s `DeleteFile()` function to delete by truncating in modestly sized chunks (preliminary tests showed that around 500MiB might be a good place to start and tune from there), and allowing the disk to recover in between.

This needs to have extensive performance tests in conjunction with #5.

**Comment by isaac-io** [comment]
This is done as part of #5.

**Comment by Guyme** [comment]
shows no value, abandoned
