### ISSUE TITLE
Paired-Bloom-Filter: Balancing rounding to batches between the bottom-most level and other levels

### ISSUE THREAD

**Issue by noamhaham** [speedb-io/speedb#369]
Improvement of the bloom filter was introduced via a more sophisticated rounding policy of the number of blocks to an integer multiplication of batch size. Some of the files are rounded up and some are rounded down. With this policy the total deviation of memory consumption from the predefined budget should be minimal.

Changes were pushed to the branch:
paired_bloom_filter_second_improvement

**Comment by mrambacher** [comment]
What is the compatibility with existing tables?  Can the original code read the new filter? 

Historically, RocksDB version X can read files written by version X+Y.  If it cannot, there will be an error thrown (like unknown version).

**Comment by noamhaham** [comment]
@mrambacher the code that was changed was only the filter builder code, the reader code is the same as the previous version so if someone created a bloom filter with the previous version and wants to read it with the new version there should be no problem.

I will push today a clean version which is based on the current main.

**Comment by erez-speedb** [comment]
Test show the same performance 
https://admin.speedb.io/performance?items=7kTr1enV1ylvhO8eT4SW&items=9RyFFS4V3KNygopMic0O&items=IvydUSWyFSXURkRFTeP8&colors=%23F06292&colors=%23BA68C8&colors=%239575CD
The major affect on the bloom performance is the number of L0 files

**Comment by erez-speedb** [comment]
@noamhaham  did you had the code review?

**Comment by erez-speedb** [comment]
Moving for QA before additional perf test.

**Comment by noamhaham** [comment]
Yes it was reviewed by Udi

**Comment by udi-speedb** [comment]
@Yuval-Ariel - Why did you assign to me?

**Comment by Yuval-Ariel** [comment]
since blackbox failed

**Comment by Yuval-Ariel** [comment]
failure seems related to 61974b12d3cd3be47eb765cf41b1f1313864463f , https://github.com/speedb-io/speedb/actions/runs/4155651486/jobs/7189154145#step:6:573 .
@mrambacher , can you take a look?
