### ISSUE TITLE
Clean data phase 1: Pinning metadata to the cache 

### ISSUE THREAD

**Issue by bosmatt** [speedb-io/speedb#388]
**Describe the solution you'd like**
Clean data refers to data that is already stored on the media. This feature is used to improve performance when accessing an object (for read and seek). 

In phase 1, the system decides on pinning the metadata when the file is opened and stays until it's closed. 
When the amount of memory in the system is enough to hold the entire metadata, this will be most beneficial. 
When the amount of the memory is not enough, the system uses priority based on the level the data is on and the metadata type. 

**Additional context**
This feature is part of the general memory manager.

**Comment by erez-speedb** [comment]
Performance tests passed, no gain no degradation.
@mrambacher the log says version 2.4.1 so please make sure it's rebased on 2.5.
Moved to QA.

**Comment by Guyme** [comment]
@Yuval-Ariel - Please review the changes @mrambacher added and please run CI

**Comment by Yuval-Ariel** [comment]
CI passed but the sanity check doesnt run on external PRs and its blocking the ability to merge.
