### ISSUE TITLE
TTL - Don't return expired objects

### ISSUE THREAD

**Issue by bosmatt** [speedb-io/speedb#394]
Currently the Get operation returns values that their ttl has expired. 
The requirement is to remove these objects from the Get output.

**Comment by ofriedma** [comment]
db_bench should work now

**Comment by ofriedma** [comment]
The test ran far more time than configured, I'm investigating it

**Comment by erez-speedb** [comment]
Run db_bench, verified the TTL cause DB reduction.
There is no actual perf test to compare, just check it won hang.
Moving to review.
