### ISSUE TITLE
`make all` fails on Fedora 35 with gcc 11.2.1 and gflags 2.2.2

### ISSUE THREAD

**Issue by AmnonHanuhov** [speedb-io/speedb#395]
**Describe the bug**
When compiling speedb (and rocksdb) on Fedora 35 with gcc 11.2.1 and gflags 2.2.2, we encounter the following error:

`
In file included from db_stress_tool/batched_ops_stress.cc:11:
./db_stress_tool/db_stress_common.h:105:15: error: expected constructor, destructor, or type conversion before ‘(’ token
  105 | DECLARE_uint32(max_num_parallel_flushes);
      |               ^ 
./db_stress_tool/db_stress_common.h:296:15: error: expected constructor, destructor, or type conversion before ‘(’ token
  296 | DECLARE_uint32(memtable_protection_bytes_per_key);
      |               ^
In file included from db_stress_tool/cf_consistency_stress.cc:11:
./db_stress_tool/db_stress_common.h:105:15: error: expected constructor, destructor, or type conversion before ‘(’ token
  105 | DECLARE_uint32(max_num_parallel_flushes);
      |               ^
./db_stress_tool/db_stress_common.h:296:15: error: expected constructor, destructor, or type conversion before ‘(’ token
  296 | DECLARE_uint32(memtable_protection_bytes_per_key);
      |               ^
  CC       db_stress_tool/no_batched_ops_stress.o
  CC       db_stress_tool/multi_ops_txns_stress.o
make: *** [Makefile:2447: db_stress_tool/batched_ops_stress.o] Error 1
`

**To Reproduce**
make all

**Expected behavior**
The build to pass

**System (please complete the following information):**
 - OS: Fedora 35
 - Hardware AMD Ryzen 7 PRO 5850U (x86_64)

**Possible solution**
Addressed [here](https://github.com/facebook/rocksdb/pull/10729). Seems to be resolved in RocksDB, but it was merged AFTER the release of RocksDB 7.7.8, which is the current RocksDB version we are rebased against.
I can open a PR with the same fix for us.

**Comment by Yuval-Ariel** [comment]
any reason not to just wait for the rebase on a version greater than 7.8.3?

**Comment by AmnonHanuhov** [comment]
> any reason not to just wait for the rebase on a version greater than 7.8.3?

Yes, because we don’t always want to rely on RockDB, especially when it comes to bug fixes. Users of speedb should be able to build speedb without issues, and should not have to rebase against RocksDB to get fixes, or make local changes. Fedora is a rather common distribution and there might be other users besides me that are experiencing this issue.
