### ISSUE TITLE
FSFileState::DropRandomUnsyncedData error

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/speedb#400]
`
==14266==ERROR: AddressSanitizer: FPE on unknown address 0x560f32c7b5a6 (pc 0x560f32c7b5a6 bp 0x7ffeb6320a30 sp 0x7ffeb6320a20 T0)

    #0 0x560f32c7b5a5 in rocksdb::FSFileState::DropRandomUnsyncedData(rocksdb::Random*) utilities/fault_injection_fs.cc:88
    #1 0x560f32c7bb0c in rocksdb::FaultInjectionTestFS::DropRandomUnsyncedFileData(rocksdb::Random*) utilities/fault_injection_fs.cc:880
    #2 0x560f31bf7720 in rocksdb::StressTest::Open(rocksdb::SharedState*) db_stress_tool/db_stress_test_base.cc:2659
    #3 0x560f31bfcabe in rocksdb::StressTest::InitDb(rocksdb::SharedState*) db_stress_tool/db_stress_test_base.cc:308
    #4 0x560f31b88b84 in rocksdb::RunStressTest(rocksdb::StressTest*) db_stress_tool/db_stress_driver.cc:76
    #5 0x560f31ac4905 in rocksdb::db_stress_tool(int, char**) db_stress_tool/db_stress_tool.cc:366
    #6 0x7f8c0245ec86 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21c86)
    #7 0x560f31abfca9 in _start (/__w/speedb/speedb/db_stress+0x2bfca9)
[logs_3768.zip](https://github.com/speedb-io/speedb/files/10729825/logs_3768.zip)

`
happens **sometimes** when running the ci.

started happening after the merging https://github.com/speedb-io/speedb/pull/380 .

**Comment by Yuval-Ariel** [comment]
@Guyme your attention. is this a critical bug @mrambacher ?

**Comment by mrambacher** [comment]
> @Guyme your attention. is this a critical bug @mrambacher ?

I think this is a problem in the test code and not the code itself.  I think when the PR was merged, a fix in the test code was accidentally reverted.
