### ISSUE TITLE
sst_dump tool should show both the offset and size from the index block handle and metaindex block handle

### ISSUE THREAD

**Issue by qianyich** [speedb-io/speedb#404]
Owner: 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by qianyich** [comment]
sst_dump tool should show both the offset and size from the index block handle and metaindex block handle

**Comment by udi-speedb** [comment]
> sst_dump tool should show both the offset and size from the index block handle and metaindex block handle

@qianyich - I am adding some information for clarification. Feel free to correct me if you think it is necessary.

When sst_dump displays the file's **footer** information, it displays the metaindex_handle and the index_handle in their encoded format (A single hexadecimal value is displayed) . A handle consists of 2 components (offset and size).
The request is to decode the handles, and display these 2 components (offset and size) explicitly, and after decoding.
