### ISSUE TITLE
db_bench doesn't support open DBWithTTL()

### ISSUE THREAD

**Issue by ofriedma** [speedb-io/speedb#417]
Currently db_bench does not support an option to benchmark DB opened with TTL(Time To Live).
The goal is to add the option for db_bench to open db with ttl, like db_stress could.
Another goal is to add skip_expired_data so it will be able to test strict ttl feature as well.

**Comment by Yuval-Ariel** [comment]
@ofriedma should this be closed since #394  is merged?
