### ISSUE TITLE
check license in all new files on every pull request 

### ISSUE THREAD

**Issue by maxb-io** [speedb-io/speedb#436]
**Describe the bug**
We need to make sure that every new file added to the project has the correct statement regarding the license
**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**System (please complete the following information):**
 - OS: [e.g. RHEL8.6]
 - Hardware [e.g. Intel Xeon Ice Lake, 64GB, NVMe]

**Additional context**

**Comment by Guyme** [comment]
already done
