### ISSUE TITLE
Enabling WF generate too much logs

### ISSUE THREAD

**Issue by erez-speedb** [speedb-io/speedb#461]
The logs for "normal" large obj test is about 30 MB, 
The WF test was over 6 GB.
In the huge 2.5 TB DB test, the logs were so big that the test failed with no space left on the device, meaning ~1 TB of logs.

**Comment by erez-speedb** [comment]
The branch reduced the logs back to normal, but also improved performance significantly ??
Small Obj
https://admin.speedb.io/performance?
items=1qSNtYwD7s1rFU6mOjiA&items=bbnH4HiAhbm13TMK0a36&items=KGP7PbR6tEVMduQAmWqW&items=eFKIsbYQ8H7XSkYOLJaM&colors=%23F06292&colors=%23BA68C8&colors=%2300796b&colors=%2300acc1&colors=%23BA68C8
 
Fillrandom X2 vs the WF before and overwrite is 50% better, makes it almost X3 more than without WF.

Large obj test is running 
@Guyme  @ayulas  @hilikspdb  FYI

**Comment by ayulas** [comment]
It does makes sense … write to log with the freq it was delayed things .. אז פצצות לגבות Sent from my iPhoneOn 14 Apr 2023, at 12:57, erez-speedb ***@***.***> wrote:﻿
The branch reduced the logs back to normal, but also improved performance significantly ??
Small Obj
https://admin.speedb.io/performance?
items=1qSNtYwD7s1rFU6mOjiA&items=bbnH4HiAhbm13TMK0a36&items=KGP7PbR6tEVMduQAmWqW&items=eFKIsbYQ8H7XSkYOLJaM&colors=%23F06292&colors=%23BA68C8&colors=%2300796b&colors=%2300acc1&colors=%23BA68C8
Fillrandom X2 vs the WF before and overwrite is 50% better, makes it almost X3 more than without WF.
Large obj test is running
@Guyme  @ayulas  @hilikspdb  FYI

**Comment by erez-speedb** [comment]
The large obj shows improved performance as well
https://admin.speedb.io/performance?items=FTIpgmv7fEWBqskYTPwa&items=vbEt4GPWB2TpQnOSCMds&items=XADjyPngf6XHviilpE0V&colors=%23F06292&colors=%23BA68C8&colors=%2300796b

However, the problems also become distinguish, the memory consumption is higher than before and the disk usage is also a scale more than without WF.

**Comment by erez-speedb** [comment]
Under the restriction, passed performance tests
