### ISSUE TITLE
Every push is causing an approve to become stale

### ISSUE THREAD

**Issue by ofriedma** [speedb-io/speedb#465]
It spends a lot of expensive time for every small change without any real affection to approve again and again we should stop stale for every push.

**Comment by Yuval-Ariel** [comment]
@udi-speedb @maxb-io , this was recently done by max per udis request as far as i know.

**Comment by udi-speedb** [comment]
> @udi-speedb @maxb-io , this was recently done by max per udis request as far as i know.

Correct. If we all think that this is not necessary, and will not abuse the approval by pushing **new** content to approved tickets, then we might as well avoid that. However, I think it must be perfectly clear that only squashes and similar may be pushed to an approved PR.

**Comment by Yuval-Ariel** [comment]
@maxb-io , can you plz disable this option? so that an approval is not revoked once something has changed in the PR

**Comment by Yuval-Ariel** [comment]
done
