### ISSUE TITLE
Investigate flaky unit tests 

### ISSUE THREAD

**Issue by assaf-speedb** [speedb-io/speedb#47]
At the moment - there are several unit tests failing in 'main'.
4 of them are mentioned here:
https://github.com/speedb-io/speedb/issues/9#issuecomment-1164276865
Since those 4 are failing in RocksDB 7.2.2 we should decide weather to fix them or remove them.
EnvTest.GenerateRawUniqueIdTrackEnvDetailsOnly
EventListenerTest.OnBlobFileOperationTest
EventListenerTest.OnFileOperationTest
EventListenerTest.ReadManifestAndWALOnRecovery

```
additional one:
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from PerfContextTest
[ RUN      ] PerfContextTest.DBMutexLockCounter
db/perf_context_test.cc:611: Failure
Expected: (get_perf_context()->db_mutex_lock_nanos) > (0), actual: 0 vs 0
terminate called after throwing an instance of 'testing::internal::GoogleTestFailureException'
  what():  db/perf_context_test.cc:611: Failure
Expected: (get_perf_context()->db_mutex_lock_nanos) > (0), actual: 0 vs 0
Aborted (core dumped)
```

As long as those tests keep failing we will not be able to make the automation process work as expected.

**Comment by Yuval-Ariel** [comment]
the issue does not reproduce on current main (1698da4cc0d66c5623916b3d083df8d42e061703) with Azure instances. all unit tests. if the problem recurs, its possible to switch to using the mock clock
