### ISSUE TITLE
PR https://github.com/speedb-io/speedb/pull/368 breaks public API compatibility

### ISSUE THREAD

**Issue by ofriedma** [speedb-io/speedb#474]
PR https://github.com/speedb-io/speedb/pull/368 breaks public API compatibility, some applications using rocksdb do not compile because of the public api changes

**Comment by Guyme** [comment]
currently paused until after the rebase

**Comment by Yuval-Ariel** [comment]
@udi-speedb , are you aware? https://github.com/speedb-io/speedb/pull/368 has been removed from the current main

**Comment by Yuval-Ariel** [comment]
updated implementation after 8.1 rebase does not change existing RocksDB public API - 
https://github.com/speedb-io/speedb/pull/620
