### ISSUE TITLE
Feature Request: Thread Affinity

### ISSUE THREAD

**Issue by Tianpingan** [speedb-io/speedb#476]
Hi Developers!

We are building a new application on top of high performance storage products, NVMe SSDs for example along with RocksDB. To fully utilize potentials of the hardware, we are using a Thread-per-Core model, similar to SPDK, Seastar and Glommio, meaning we need to dedicate a few cores to them. 

After investigation, we see two options: isolcpus and thread-affinity. We rule out the former as it is not flexible enough and does not meet deployment requirements.  RocksDB is extensible through Env, where Filesystem, etc are abstracted. Unfortunately, I do not see a good place to plug thread affinity in.

A preliminary attempt is made [here](https://github.com/lizhanhui/rocksdb/commit/3a67d7667f776b72899b677eba157deca8be8a27).

**Comment by Tianpingan** [comment]
> We can add an callback to the env "on_thread_starts" and call it with the relevant parameters , the user will need to implement the callback and change the attributes of the thread.

Thank you! 
what can I do for this issue to help you

**Comment by erez-speedb** [comment]
Passed perf tests
