### ISSUE TITLE
SpeedB WF memory consumption 

### ISSUE THREAD

**Issue by erez-speedb** [speedb-io/speedb#485]
Ruuning the same test on the same sha with and without speedb WF 
There is indeed almost X2 write performance gain but the memory consumption also jumps

https://admin.speedb.io/performance?items=Gx31iUGYxMJMDVLVllRC&items=qDTnAvLGLWV43H0tncys&colors=%23F06292&colors=%23BA68C8

**Comment by Guyme** [comment]
@ayulas - status ?

**Comment by ayulas** [comment]
wa solved ages ago as part of read lock priority issue

**Comment by erez-speedb** [comment]
Which branch solves this?
