### ISSUE TITLE
gtest parallel: leftover cache

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/speedb#486]
file - gtest_parallel.cpython-38.pyc is created during make check and is not deleted nor is it added in gitignore. 
file is created in  - build_tools/__pycache__/

related to #261

**Comment by Yuval-Ariel** [comment]
@AmnonHanuhov  can you take a look plz?

**Comment by AmnonHanuhov** [comment]
> @AmnonHanuhov can you take a look plz?

On it

**Comment by Yuval-Ariel** [comment]
setting to "On Hold" until we've rebased on 8.1.1
