### ISSUE TITLE
db_stress: Assertion in filter_policy.cc when using Paired Bloom Filter

### ISSUE THREAD

**Issue by udi-speedb** [speedb-io/speedb#488]
The db_stress fails on an assertion in filter_policy.cc:
`assert(target_len < target_len_with_metadata)

`Reproduction: 
`CRASH_TEST_EXT_ARGS="--filter_uri=speedb.PairedBloomFilter" make blackbox_crash_test`

**Comment by Yuval-Ariel** [comment]
plz also re enable the stress testing of the paired filter which was disabled as part of 21ff6ca94b9a1bd29f2be7c9c6ce7050757752aa .

**Comment by udi-speedb** [comment]
The assertion that I am able to reproduce and has also been seen by @hilikspdb is not the one in the description above but the following (line 185 in filter_policy.cc):
```
rv = RoundDownUsableSpace(usable - kExtraPadding);
assert(rv <= usable - kExtraPadding);
```

**Comment by hilikspdb** [comment]
Do any of these asserts would lead to data corruption or system failure or
are they just DEBUG assert that should not exist in the code?

**Comment by udi-speedb** [comment]
This is an assertion in a common RocksDB code that our bloom filter uses. It is a valid assertion and needs our fixing.

**Comment by udi-speedb** [comment]
I have opened https://github.com/speedb-io/speedb/issues/541 to properly support sanitization of block based table options such as the one needed in this issue - The optimize_filters_for_memory.
Specifically, this is a block based table option. It should be sanitized only when there is a filter policy and when that filter policy is our (plug-in) paired bloom filter.
However, we can't add code to check that it's the paired bloom filter in the rocksdb, plug-in agnostic code.
I am currently doing it in the code of the filter itself, not part of any sanitization code (just assuming a certain value for the option that is supported by our paired bloom filter)
