### ISSUE TITLE
Index size Per CF in Block Cache Feature broken after rebase on RocksDB 8.1 (LRU Cache)

### ISSUE THREAD

**Issue by udi-speedb** [speedb-io/speedb#516]
Facebook have made sunstantial modifications to the Block Cache API. The speedb feature needs adaptations.

While working on this issue, consider https://github.com/speedb-io/speedb/issues/474

**Comment by udi-speedb** [comment]
The original issue is: https://github.com/speedb-io/speedb/issues/338

**Comment by Guyme** [comment]
@erez-speedb - Please run Performance

**Comment by erez-speedb** [comment]
Performance test of 32CF, 2GB cache passed

**Comment by Guyme** [comment]
@Yuval-Ariel - Please make your checks and merge. thanks
