### ISSUE TITLE
Proactive Flushes: Failure to decrement num_flushes_to_initiate_ when a non-wbm flush starts

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/speedb#523]
num_flushes_to_initiate_ is not decremented when a flush starts that hasnt been initiated by the WBM. 
num_running_flushes_ and num_flushes_to_initiate_ leads the InitiateFlushesThread thread to decide whether to initiate an additional flush request. 
not decrementing the num_flushes_to_initiate_ can lead to scheduling more flushes than required.

**Comment by Guyme** [comment]
@Yuval-Ariel - Ready to merge ?

**Comment by erez-speedb** [comment]
Passed perf tests
