### ISSUE TITLE
LOG improvement: CF-s' Stats may be cropped when there is a lot of information (many cf-s)

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/speedb#534]
The CF-specific statistics (Compaction Stats, File Read Latency, etc.) for all of the cf-s is included in a single LOG entry.
There is a limit on the max size of a LOG entry. Any text not within the limit is cropped and the text is not displayed. Therefore, when there are a relatively large number of cf-s, the stats may be cropped and important information will be lost.

cmd to reproduce:
db_bench --compression_type=None -db=/data/ -num=2500000000 -value_size=1000 -key_size=16 --delayed_write_rate=536870912 -report_interval_seconds=1 -max_write_buffer_number=6 -num_column_families=30 -histogram -max_background_compactions=8 -max_background_flushes=4 -bloom_bits=10 -benchmark_read_rate_limit=0 -benchmark_write_rate_limit=0 -report_file=fillrandom.csv --disable_wal=true --benchmarks=fillrandom,levelstats -max_background_jobs=20 -max_write_buffer_number=6 -write_buffer_size=268435456 -target_file_size_base=1073741824

also during first Compaction Stats dump there can be more that 17 printed but the last one could be cut off.

**Comment by udi-speedb** [comment]
@Yuval-Ariel The limit is the size of the text, not the number of cf-s.
