### ISSUE TITLE
LOG Improvement: Sum W-amp might have a bug

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/speedb#535]
value of Sum W-amp is 0 when it shouldnt
![image](https://github.com/speedb-io/speedb/assets/105581454/70f9482a-7b80-47bb-bb2e-d0bb8554537c)

cmds: 
--benchmarks=fillrandom  --num_column_families=3 --column_family_distribution=10,30,60 --write_buffer_size=30085760 --stats_dump_period_sec=30 --compression_type=None --num=5000000  --seed=0 -cache_size=222200000 --statistics=1 --delayed_write_rate=536870912 -value_size=1000 

then same with --use_existing_db --benchmarks=readrandom --duration=61

**Comment by udi-speedb** [comment]
@Yuval-Ariel - Is this upstreamable?
If it is, please add an label. Thanks

**Comment by Yuval-Ariel** [comment]
might be upstreamable. need to check in rocksdb.

**Comment by udi-speedb** [comment]
I will try to reproduce on both Speedb's latest and on RocksDB
