### ISSUE TITLE
Is Sorted Hash Memtable supported via Java API?

### ISSUE THREAD

**Issue by KKcorps** [speedb-io/speedb#548]
I can't find the JNI code to use this memtable implementation

Also, is there a way to use `spdb_write_flow` in Java?

**Comment by ayulas** [comment]
currently it doesnt but i will add it under this ticket. tnx

**Comment by KKcorps** [comment]
Thanks a lot!

**Comment by Yuval-Ariel** [comment]
plz also update the HISTORY.md file
