### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by eladn** [speedb-io/speedb#554]
We're running machine-learning offline learning flows which involve heavy disk IOs (both read & writes). Our offline codebase is entirely written in python, as it's a research-oriented project and thus evolves rapidly. We would like to use a solution like speedb directly from python code. However, it seems that there are currently no available up-to-date and well-maintained python bindings neither for "vanilla" RocksDB nor for speedb. It would be great to have such.

**Comment by Congyuwang** [comment]
https://github.com/Congyuwang/RocksDict/releases/tag/speedict-v0.3.11

**Comment by bosmatt** [comment]
@eladn I'm closing this issue, following the previous comment. Please let us know if anything else is needed.
