### ISSUE TITLE
Simultaneous read and write instances

### ISSUE THREAD

**Issue by eladn** [speedb-io/speedb#562]
Is it possible to have multiple instances simultaneously accessing the same db, where some insurances use read-mode while one instance is opened in write-mode? We're fine about not being able to read data that is still located in the writer's memtable or in sstables that are not flushed yet.

**Comment by Guyme** [comment]
Hi Elad,
Yes, it is possible, it is done by opening the database as secondary.
We have a nice example code on how to run it including catchups [here](https://github.com/speedb-io/speedb/blob/secondary_db_example/examples/secondary_db.cc) 
closing the issue - happy to provide follow-up answers in our [Discord ](https://discord.gg/deMznf8aZZ)
