### ISSUE TITLE
Cache: Block Cache stats seems broken

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/speedb#576]
Block cache entry stats doesnt show cached index and data blocks as it should when running db bench with -cache_index_and_filter_blocks=true and a block cache with a read benchmark (tested readrandom and readrandomwriterandom) after filling it up with 5Gb.
Block cache LRUCache@0x563268152150#445727 capacity: 220.00 MB usage: 0.09 KB table_size: 256 occupancy: 96 collections: 1 last_copies: 3 last_secs: 6e-05 secs_since: 6
Block cache entry stats(count,size,portion): Misc(1,0.00 KB,0%)
 
exact cmd:
`./db_bench --compression_type=None -db=/data/ -num=10000000 -value_size=1000 -key_size=200 --delayed_write_rate=536870912 -report_interval_seconds=1 -max_write_buffer_number=4 -num_column_families=1 -histogram -max_background_compactions=8 -cache_size=220000000 -max_background_flushes=4 -report_file=fillrandom.csv --disable_wal=true --benchmarks=readrandom,stats -stats_dump_period_sec=30 --duration=150 -cache_index_and_filter_blocks=true -cache_high_pri_pool_ratio=1 --use_existing_db`

This happens with rocksdb as well (base/v7.7.8 and base/v8.1.1)

**Comment by Yuval-Ariel** [comment]
the block cache stats are simply collected separately from the other stats (seems like every 3 mins) and then that info is dumped with the db stats. running the above with longer duration shows that the block cache entries are populated as expected. @udi-speedb  FYI

**Comment by udi-speedb** [comment]
> the block cache stats are simply collected separately from the other stats (seems like every 3 mins) and then that info is dumped with the db stats. running the above with longer duration shows that the block cache entries are populated as expected. @udi-speedb FYI

Glad to hear that. Thanks for checking.
