### ISSUE TITLE
Cannot delete default column family

### ISSUE THREAD

**Issue by mjsax** [speedb-io/speedb#583]
This is a duplication of https://github.com/facebook/rocksdb/issues/10138, that was rejected by RocksDB folks.

It's an issue for Kafka Streams. Cf https://issues.apache.org/jira/browse/KAFKA-13973 that we cannot resolve without the ability to delete the default column family.

**Comment by mjsax** [comment]
Question: Why do we actually get doubled block-cache-capacity _and also_ double block-cache **_usage_**? If we set block-cache-capacity to X, is the capacity assigned per column family, and thus capacity doubles? But the underlying block cache is still shared across both column families and thus even if we only use one of both column families, it has access to 2*X memory (ie, everything that was allocated)?

**Comment by hilikspdb** [comment]
Delete of the default CF in the Rocksdb code is "almost" impossible, the code assumes that the first CF is the "default" and changing this assumption require changes in the code in many places. This is probably this issue was rejected by the rocksdb team.  
As for the setting of the cache: if you use the "cache_size"  option, the code assumes it is one per CF and create a seperate cache object for each CF.  On the other hand you can create a cache object and assign it to as many CF as you want.

 Hence the problem described above can be resolved by either sharing the cache between all the CF or else open the database with a no_cache flags set to true for the default CF and other cf with a different value.  Usually we recommend sharing the cache (and maybe increase the number of shards in the cache)

**Comment by Guyme** [comment]
@mjsax The block cache may be shared by multiple cf-s in the same db or across multiple db-s. Speedb / Rocksdb log displays the use of the block cache in an aggregated manner. One can't tell how much of the cache's capacity is used by the individual cf-s sharing a cache.
In our recently released 2.6 release we have re-enabled the per CF memory reporting feature.
With this feature enabled we report to the log additional information that informs the memory each CF consumes of the total block cache capacity. Looking at this information would allow you to see how much memory is consumed by the default cf. We expect it to be close to 0 when it has no data thus allowing you to be agnostic to its existence.

In addition, we have added the capability to query Speedb programmatically (via the standard GetProperty() API) for this information (per-cf block cache use). In our 2.6 release it is available only in C++. We will expose it to JAVA (via the JNI) in the next release. That will allow you to perform per-cf live monitoring in Kafka Streams.

**Comment by mjsax** [comment]
Thank a lot for the information!

> In our recently released 2.6 release we have re-enabled the per CF memory reporting feature.

That's sounds very useful!

In the meantime, we got the following PR trying to fix the issue on our side. In case you want to have a look and confirm that this fix would make sense or not (not now): https://github.com/apache/kafka/pull/14317

**Comment by udi-speedb** [comment]
> Thank a lot for the information!
> 
> > In our recently released 2.6 release we have re-enabled the per CF memory reporting feature.
> 
> That's sounds very useful!
> 
> In the meantime, we got the following PR trying to fix the issue on our side. In case you want to have a look and confirm that this fix would make sense or not (not now): [apache/kafka#14317](https://github.com/apache/kafka/pull/14317)

I have looked at [https://github.com/apache/kafka/pull/14317](url). As long as all of your cf-s share the same cache, it will work. As I have explained above, the usage values you are seeing are not for any specific CF, but for the entire cache.

@mjsax - In view of all of the above, is this issue still applicable? Do you see any need to delete the default column family?

**Comment by cadonna** [comment]
IMO, if the default column family does not consume any resources we do not need to delete the default column family. As far as I understand, the default column family does not consume any cache or memtables, if it is empty, right?

**Comment by udi-speedb** [comment]
Yes
