### ISSUE TITLE
deadlock in write _thread linkone function during stall

### ISSUE THREAD

**Issue by ayulas** [speedb-io/speedb#637]
deadlock stall

**Comment by ayulas** [comment]
the thread which begin the stall:

 futex_wait_cancelable (private=<optimized out>, expected=0,
    futex_word=0x7f632d86dec8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f632d86de78,
    cond=0x7f632d86dea0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7f632d86dea0, mutex=0x7f632d86de78)
    at pthread_cond_wait.c:647
#3  0x00005632819bffe1 in rocksdb::port::CondVar::Wait (this=<optimized out>)
    at port/port_posix.cc:119
#4  0x00005632817dfea1 in rocksdb::DBImpl::WBMStallInterface::Block (
    this=0x7f632d86de70) at ./db/db_impl/db_impl.h:1249
#5  rocksdb::DBImpl::WriteBufferManagerStallWrites (this=0x7f632d87ec00)
    at db/db_impl/db_impl_write.cc:1932
#6  0x00005632817e54fa in rocksdb::DBImpl::PreprocessWrite (
    this=<optimized out>, write_options=..., log_context=0x7f62c85d5660,
    write_context=<optimized out>) at db/db_impl/db_impl_write.cc:1228
#7  0x00005632817e99de in rocksdb::DBImpl::WriteImpl (this=0x7f632d87ec00,
    write_options=..., my_batch=<optimized out>, callback=<optimized out>,
    log_used=<optimized out>, log_ref=<optimized out>,
    disable_memtable=<optimized out>, seq_used=<optimized out>,
    batch_cnt=<optimized out>, pre_release_callback=<optimized out>,
    post_memtable_callback=<optimized out>) at db/db_impl/db_impl_write.cc:391
#8  0x00005632817ead44 in rocksdb::DBImpl::Write (this=0x7f632d87ec00,
    write_options=..., my_batch=0x7f62c85d5da0)
    at db/db_impl/db_impl_write.cc:146


the call WriteBufferManagerStallWrites is under db mutex which leads to a potential dead lock incase  WriteThread::LinkOne getting into stall wait.

**Comment by ayulas** [comment]
there is a race that wbm stall doesnt trigger the flush so the mem is not free. therefor the stall will never ended and all the writes are stucked

in the current machine thread 58 is the wbm stall:

(gdb) bt
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f632d86dec8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f632d86de78, cond=0x7f632d86dea0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7f632d86dea0, mutex=0x7f632d86de78) at pthread_cond_wait.c:647
#3  0x00005632819bffe1 in rocksdb::port::CondVar::Wait (this=<optimized out>) at port/port_posix.cc:119
#4  0x00005632817dfea1 in rocksdb::DBImpl::WBMStallInterface::Block (this=0x7f632d86de70) at ./db/db_impl/db_impl.h:1249
#5  rocksdb::DBImpl::WriteBufferManagerStallWrites (this=0x7f632d87ec00) at db/db_impl/db_impl_write.cc:1932
#6  0x00005632817e54fa in rocksdb::DBImpl::PreprocessWrite (this=<optimized out>, write_options=..., log_context=0x7f62c85d5660, write_context=<optimized out>) at db/db_impl/db_impl_write.cc:1228
#7  0x00005632817e99de in rocksdb::DBImpl::WriteImpl (this=0x7f632d87ec00, write_options=..., my_batch=<optimized out>, callback=<optimized out>, log_used=<optimized out>, log_ref=<optimized out>, disable_memtable=<optimized out>,
    seq_used=<optimized out>, batch_cnt=<optimized out>, pre_release_callback=<optimized out>, post_memtable_callback=<optimized out>) at db/db_impl/db_impl_write.cc:391
#8  0x00005632817ead44 in rocksdb::DBImpl::Write (this=0x7f632d87ec00, write_options=..., my_batch=0x7f62c85d5da0) at db/db_impl/db_impl_write.cc:146
#9  0x00005632817eb07a in rocksdb::DB::Put (this=0x7f632d87ec00, opt=..., column_family=0x7f6322bc29c0, key=..., value=...) at db/db_impl/db_impl_write.cc:2349
#10 0x00005632817eb204 in rocksdb::DBImpl::Put (this=this@entry=0x7f632d87ec00, o=..., column_family=0x7f6322bc29c0, key=..., val=...) at db/db_impl/db_impl_write.cc:28
#11 0x00005632816f1a84 in rocksdb::Benchmark::ReadRandomWriteRandom (this=0x7f632d893a00, thread=0x7f6321502400) at tools/db_bench_tool.cc:7974
#12 0x00005632816e73d6 in rocksdb::Benchmark::ThreadBody (v=0x7f632d927668) at tools/db_bench_tool.cc:4210
#13 0x00005632819127c9 in rocksdb::(anonymous namespace)::StartThreadWrapper (arg=0x7f632d868c70) at env/env_posix.cc:461
#14 0x00007f632e3e2609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007f632de8e133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95


ongoing writes are stuck on that stall

(gdb) bt
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f632d87fb50) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f632d87fb00, cond=0x7f632d87fb28) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7f632d87fb28, mutex=0x7f632d87fb00) at pthread_cond_wait.c:647
#3  0x00005632819bffe1 in rocksdb::port::CondVar::Wait (this=<optimized out>) at port/port_posix.cc:119
#4  0x00005632818f538c in rocksdb::WriteThread::LinkOne (this=0x7f632d87f9c0, w=0x7f62c7dd47a0, newest_writer=0x7f632d87f9e8) at db/write_thread.cc:248
#5  0x00005632818f589b in rocksdb::WriteThread::JoinBatchGroup (this=0x7f632d87f9c0, w=0x7f62c7dd47a0) at db/write_thread.cc:405
#6  0x00005632817e9520 in rocksdb::DBImpl::WriteImpl (this=0x7f632d87ec00, write_options=..., my_batch=<optimized out>, callback=0x0, log_used=0x0, log_ref=0, disable_memtable=false, seq_used=0x0, batch_cnt=0, pre_release_callback=0x0,
    post_memtable_callback=0x0) at db/db_impl/db_impl_write.cc:318
#7  0x00005632817ead44 in rocksdb::DBImpl::Write (this=0x7f632d87ec00, write_options=..., my_batch=0x7f62c7dd4da0) at db/db_impl/db_impl_write.cc:146
#8  0x00005632817eb07a in rocksdb::DB::Put (this=0x7f632d87ec00, opt=..., column_family=0x7f6322bc28c0, key=..., value=...) at db/db_impl/db_impl_write.cc:2349
#9  0x00005632817eb204 in rocksdb::DBImpl::Put (this=this@entry=0x7f632d87ec00, o=..., column_family=0x7f6322bc28c0, key=..., val=...) at db/db_impl/db_impl_write.cc:28
#10 0x00005632816f1a84 in rocksdb::Benchmark::ReadRandomWriteRandom (this=0x7f632d893a00, thread=0x7f632150a000) at tools/db_bench_tool.cc:7974
#11 0x00005632816e73d6 in rocksdb::Benchmark::ThreadBody (v=0x7f632d927690) at tools/db_bench_tool.cc:4210
#12 0x00005632819127c9 in rocksdb::(anonymous namespace)::StartThreadWrapper (arg=0x7f632d868c80) at env/env_posix.cc:461
#13 0x00007f632e3e2609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#14 0x00007f632de8e133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by erez-speedb** [comment]
@udi-speedb  @ayulas  Can the instance be destroyed?

**Comment by ayulas** [comment]
I did some work on it so tomorrow is ok ?

**Comment by erez-speedb** [comment]
@ayulas  no linked PR yet

**Comment by ayulas** [comment]
There is 
https://github.com/speedb-io/speedb/pull/683

**Comment by Guyme** [comment]
@ayulas - status please.
also please verify that #683 is indeed the code for this deadlock (the content seams to be something else - history updates referes #653)
