### ISSUE TITLE
move hashSpdb memtable from plugin to main code 

### ISSUE THREAD

**Issue by ayulas** [speedb-io/speedb#639]
move hashSpdb memtable from plugin to main code

**Comment by mrambacher** [comment]
Why do we want to do this?  The more changes to core RocksDB, the harder it is to merge with the meta and other versions.

**Comment by ayulas** [comment]
from the beginning  it was a bad decision and i was against this. but the most important is that spdb memtable requires prepare switch mechanism which is part of main so the plugin  for memtable is broken and doesnt stand alone. personally i dont see any benefit for the plug at all. and regarding the merge in this case is not true since this is completely differnt file and any change inside touch  only the hash_spdb files.

**Comment by mrambacher** [comment]
> from the beginning it was a bad decision and i was against this. but the most important is that spdb memtable requires prepare switch mechanism which is part of main so the plugin for memtable is broken and doesnt stand alone. personally i dont see any benefit for the plug at all. and regarding the merge in this case is not true since this is completely differnt file and any change inside touch only the hash_spdb files.

The code for the memtable should be a plugin.  It is simply an alternate implementation of a memtable.  

Every time speedb makes an API change to RocksDB, you remove some of the drop-in replacement ability.  If a user needs to talk the Speedb API, they will have to update their application to use the speedb features.  This eliminates the ability to be use the release without code changes.  That is one of the main points of being able to do these plugin replacements via Options and Plugins.
