### ISSUE TITLE
java wrapper

### ISSUE THREAD

**Issue by patelprateek** [speedb-io/speedb#641]
Currently I am using rockdb jni in some of our indexing pipeline to index terabyte scale data .
I would like to try speeddb  integration to our indexing and serving backends to test out performance , cost , scalability.

Can you provide some pointers about if there is any jni bindings rimilar to maven rocksdbjni  that I can do some quick experiments with.

Also for better understanding , can you also porivde some pointers to kind of optimizations speeddb has done on top of rocksdb 
What new parameters i would need to configure apart from typical rocksdb option file , any pointers would be very appreciated

**Comment by Guyme** [comment]
Hi @patelprateek .
Speedb JNI is available through maven here - https://mvnrepository.com/artifact/io.github.speedb-io
For specific speedb features you can see them all in our documentation - https://docs.speedb.io/speedb-features
Not all of them are exposed in the java interface yet, we are working on it.
If you have a specific need, or if you want to to share your usecase and get assistance in configuration we are happy to do that on our discord channel - https://discord.com/invite/deMznf8aZZ

Closing this issue as there is no bug\feature - let's move the configuration part to discord
