### ISSUE TITLE
Log Improvement: Rearrange Block cache stats dump in the log

### ISSUE THREAD

**Issue by udi-speedb** [speedb-io/speedb#658]
Currently the Block cache entry stats are displayed per cf (in the log file).

In RocksDB, there are 2 identical lines displayed per CF. These report the aggregated block cache usage stats (these are not maintained per CF). However, they are duplicated for every CF in every DB stats dump. This may be misleading for users that may think the information is specific for a CF.

For example:
```
Block cache LRUCache@0x55977f0dd670#46392 capacity: 46.97 GB usage: 23.18 GB table_size: 8388608 occupancy: 2132017776 collections: 2 last_copies: 59 last_secs: 2.16855 secs_since: 240
Block cache entry stats(count,size,portion): DataBlock(5311394,20.48 GB,43.6113%) FilterBlock(1936,1.63 GB,3.46368%) IndexBlock(1934,553.03 MB,1.14985%) WriteBuffer(865,216.25 MB,0.449622%) Misc(1,0.00 KB,0%)
```

In Speedb, an additional lines is displayed (see #516 ). This third line contains data specific to the CF.
So, in Speedb's case, it would look like this:

```
Block cache LRUCache@0x55977f0dd670#46392 capacity: 46.97 GB usage: 23.18 GB table_size: 8388608 occupancy: 2132017776 collections: 2 last_copies: 59 last_secs: 2.16855 secs_since: 240
Block cache entry stats(count,size,portion): DataBlock(5311394,20.48 GB,43.6113%) FilterBlock(1936,1.63 GB,3.46368%) IndexBlock(1934,553.03 MB,1.14985%) WriteBuffer(865,216.25 MB,0.449622%) Misc(1,0.00 KB,0%)
Block cache [default]  DataBlock(1.76 GB) FilterBlock(140.59 MB) IndexBlock(46.68 MB)
```

This feature proposal is to have, per DB stats dump, a single, separate block cache stats section, that will look as follows (more or less, exact formatting will be determined later):
```
** Block Cache Stats **
Block cache LRUCache@0x55977f0dd670#46392 capacity: 46.97 GB usage: 1.74 GB table_size: 5216 occupancy: 1873305024 collections: 1 last_copies: 11 last_secs: 0.000739 secs_since: 0
Block cache entry stats(count,size,portion): FilterBlock(1500,1.31 GB,2.78624%) IndexBlock(1500,445.95 MB,0.9272%) WriteBuffer(1,256.00 KB,0.000519794%) Misc(2,4.06 KB,8.24868e-06%)
Block cache [default]  DataBlock(0.00 KB) FilterBlock(112.01 MB) IndexBlock(37.27 MB)
Block cache [column_family_name_000001]  DataBlock(0.00 KB) FilterBlock(112.12 MB) IndexBlock(37.32 MB)
Block cache [column_family_name_000002]  DataBlock(0.00 KB) FilterBlock(112.33 MB) IndexBlock(37.39 MB)
Block cache [column_family_name_000003]  DataBlock(0.00 KB) FilterBlock(110.72 MB) IndexBlock(36.84 MB)
```
So, the global data will be displayed once, followed by a single line per cf, and will replace the existing per-CF dump.

**Comment by git-hulk** [comment]
@udi-speedb Can I take this task if no one is working on it?

**Comment by udi-speedb** [comment]
> @udi-speedb Can I take this task if no one is working on it?

I apologize for the long delay in replying, I was away and now I am back.

As for working on this issue, you are welcome to take it. Thanks for that.

**Comment by git-hulk** [comment]
@udi-speedb Sorry for missing this issue. I'm not working on this issue for now, but I will do it soon.

**Comment by git-hulk** [comment]
Hi @udi-speedb I have a question about this. What if two columns are using the same block cache? should we print them twice? It may confuse users.

**Comment by udi-speedb** [comment]
I am not sure I understand why there should be a confusion.
For example, in the following imaginary output I am showing 4 column families sharing the same cache:
```
** Block Cache Stats **
Block cache LRUCache@0x55977f0dd670#46392 capacity: 46.97 GB usage: 1.74 GB table_size: 5216 occupancy: 1873305024 collections: 1 last_copies: 11 last_secs: 0.000739 secs_since: 0
Block cache entry stats(count,size,portion): FilterBlock(1500,1.31 GB,2.78624%) IndexBlock(1500,445.95 MB,0.9272%) WriteBuffer(1,256.00 KB,0.000519794%) Misc(2,4.06 KB,8.24868e-06%)
Block cache [default]  DataBlock(0.00 KB) FilterBlock(112.01 MB) IndexBlock(37.27 MB)
Block cache [column_family_name_000001]  DataBlock(0.00 KB) FilterBlock(112.12 MB) IndexBlock(37.32 MB)
Block cache [column_family_name_000002]  DataBlock(0.00 KB) FilterBlock(112.33 MB) IndexBlock(37.39 MB)
Block cache [column_family_name_000003]  DataBlock(0.00 KB) FilterBlock(110.72 MB) IndexBlock(36.84 MB)
```
Today the last 4 lines (one per each cf) appear separated in the log.
The line just above these 4 lines is the one that shows the total for the block cache, and it appears once per (shared) block cache.

**Comment by git-hulk** [comment]
@udi-speedb Thanks for your explain. I misunderstood what issue described. Let me repeat your reply, correct if I was wrong.

For example, if CF0,CF1,CF2 are sharing the block cache `B0` and CF3, CF3 are sharing `B1`, and what we want is:

Line 0: show the total for `B0`
Line 1: show CF0
Line 2: show CF1
Line 3: show CF2
Line 4: show the total for `B1`
Line 5: show CF3
Line 6: show CF4

And CF0+CF1+CF2 = Total size of B0, CF3+CF4 = Total size of B1

Is that right?

**Comment by udi-speedb** [comment]
Hi,
Almost:
- The Block cache may be shared by multiple db-s => cf0 + cf1 + cf2 will be the total size of B0 only if there **isn't** additional db-s in which cf-s are sharng B0.
- There are 2 non-cf-specific lines per the entire block cache (B0 / B1 / ...):
 there are actually 2 lines
