### ISSUE TITLE
Static Pinning: Incorrect decision on bottom level

### ISSUE THREAD

**Issue by udi-speedb** [speedb-io/speedb#662]
When creating a table reader, an is_bottom flag is calculated based on the table's level.
However, the decision is using the immutable options' num_levels option to determine if the table is the bottom-most or not.

The decision should be based on the actual state of the LSM, by searching for the bottom most level in the current VersionStorageInfo.

**Comment by hilikspdb** [comment]
The code is broken in rocksdb. The decision on is bottom-most is done based on the parameter num_levels (static options) and not on the last level that actually has data. This creates the following erroneous behaviour: 

-  Optimise filter for hit (meaning no bloom filter for bottom-most level may not work (needed to be checked , maybe during the build the code sets it correctly)
- Ingest behind creates an LSM tree that has files in L6 while the database size does not justified it (issue afterword for compaction)  
- pinning decisions treats the bottom-most level as any other level 
- (caching decisions can not be made based on this flag )

**Comment by mrambacher** [comment]
In TableCache::GetTableReader, the code checks to see if the file is at the bottom level by comparing level to the number of levels.   Changing the code here to better check "bottom" would change how caching and pinning behaves.

I am not certain on the other two (optimize filter and ingest) behaviors and if those are meant to be on "last" or "bottom" level.

**Comment by hilikspdb** [comment]
- If you use the last level than most of the time the set of files is empty (except if the user is doing inject behind I have never saw files in L6) 
- (ingest behind) creating files in the last level when the LSM tree does not need it , makes the calculation of space amplification impossible. If you use dynamic level it will lead to huge write amplification etc.. 
- optimise filter for hits   means that the user knows that the data she is searching for exists in the database. No point in holding bloom on the bottom-most level in this case (since this code is in table-reader and the decision if to build bloom is in the table builder this decision may be done correctly please check) ..

**Comment by udi-speedb** [comment]
This issue will only handle the **static pinning related flag**. 
The general topic of bottom level will be part of  #@665

To make it clear, I will use last_level_with_data rather than is_bottom in the applicable static pinning code.

**Comment by erez-speedb** [comment]
Ran the pinning test, results are same for 1 &8 GB cache and better with 3GB cache.
@hilikspdb  @udi-speedb  as expected?
https://admin.speedb.io/performance?items=lRaFlxp9bNZCPPzLafiG&items=FfcRwXNgMwvkxDUt5HMm&colors=%23F06292&colors=%2300796b
https://admin.speedb.io/performance?items=ELpsIrjr9FIsCfz9VTaJ&items=LHDAYjObpeYEC9t2P9sy&colors=%23F06292&colors=%2300796b
https://admin.speedb.io/performance?items=ZblSG23iJCEEF6YMD6Jx&items=h3EJlENg02dipEIhdv43&colors=%23F06292&colors=%2300796b

**Comment by hilikspdb** [comment]
one more thing to test is with compression (or with bottomost compression)
, this will make the read from the OS much more expensive ...

**Comment by udi-speedb** [comment]
@erez-speedb I suggest to wait for #687 and #691 to be merged into main and then run performance tests on static pinning.

**Comment by erez-speedb** [comment]
nothing performance related here, moving to qa
