### ISSUE TITLE
CI: Check-Licence-And-History failing 

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/speedb#682]
we need to understand whether we should update license in changed files or just in new files.
also, the list of changed files might be off

**Comment by git-hulk** [comment]
Hi @Yuval-Ariel 

Looks like the `Check License And History` CI has two issues:

- Should checkout repository before running job
- Check license should be only for new file, so need to remove other filter types except `A`

Is it right? If yes, then I would like to file a PR to fix this.

**Comment by Yuval-Ariel** [comment]
hey @git-hulk  thanks for your engagement! 
We're not sure whether the Check license should run only on new files or also modified. @Guyme is looking into it

**Comment by git-hulk** [comment]
@Yuval-Ariel Sure, thank you! @Guyme can ping me back if it's good to go.

**Comment by Yuval-Ariel** [comment]
works fine now as far as i can tell. @git-hulk  thanks!
