### ISSUE TITLE
Defaults for scoped policy pinning should be 70% for last level with data and 90% for non-level 0 (mid-percent)

### ISSUE THREAD

**Issue by udi-speedb** [speedb-io/speedb#689]

**Comment by erez-speedb** [comment]
@udi-speedb @hilikspdb based on what were those numbers chosen?

**Comment by hilikspdb** [comment]
The numbers are just an approximation the reasons are:
 

1. L0 index & filters sizes are usually bounded to less than 100-200MB (assuming there is about 0.5 - 1G in them) hence I do not see a reason to give the more.
2. if the system has ~80-90 % of he data in the bottom-most than most of the time the 20% extra memory for the middle layer will be enough.. 

Please remember this is only a stage toward cache planing where we will give up those artificial limits  and use cache tuning instead....

**Comment by erez-speedb** [comment]
@hilikspdb  @udi looks at those results
https://admin.speedb.io/performance?items=5KjDSOajBK5mdqdRPS3L&items=ymFnz5ZJWXvM4NggP4AZ&items=hGNXsDgTosQOHxVs1pXk&colors=%23F06292&colors=%23BA68C8&colors=%2300796b
The compare between 70 90  to 65 75  to 10  80
Looks like 10 80 gives the best read performance and 65 75 the worse.

**Comment by udi-speedb** [comment]
> @hilikspdb @udi looks at those results https://admin.speedb.io/performance?items=5KjDSOajBK5mdqdRPS3L&items=ymFnz5ZJWXvM4NggP4AZ&items=hGNXsDgTosQOHxVs1pXk&colors=%23F06292&colors=%23BA68C8&colors=%2300796b The compare between 70 90 to 65 75 to 10 80 Looks like 10 80 gives the best read performance and 65 75 the worse.

@hilikspdb:
1. 10/80 are the current defaults in the code. What do you make of these results?
2. Do we close this issue and leave the defaults as is?
3. Do we want to perform additional tests (in that case we must specify what configuration to use)?

**Comment by hilikspdb** [comment]
My view is that 50-70 performs better (when the tests started 10-70 is looking better but these advantages disappear after a while) . I would not want to see systems that have large cache not pinning because we were too conservative ... 
@erez-speedb  if you may please also run the tests with 60GB of cache. 
Thanks

**Comment by udi-speedb** [comment]
I will work on this issue only once we have an agreed defaults that we decide to use.

**Comment by udi-speedb** [comment]
@erez-speedb - Where does this stand?
Is there anything to do about this or do we have a decision?

**Comment by erez-speedb** [comment]
@udi-speedb  based on the results of https://github.com/speedb-io/scripts/issues/24 and a quick meeting with @Guyme and @hilikspdb  
Pls set the defaults to bottom_percent=10 mid_percent=70

For large cache (x3 index sizes), we understand that bottom_percent to increase to 40% or 50%

**Comment by udi-speedb** [comment]
> @udi-speedb based on the results of [speedb-io/scripts#24](https://github.com/speedb-io/scripts/issues/24) and a quick meeting with @Guyme and @hilikspdb Pls set the defaults to bottom_percent=10 mid_percent=70
> 
> For large cache (x3 index sizes), we understand that bottom_percent to increase to 40% or 50%

@erez-speedb I do not understand.
It's a single value. Do you want the value to be adapted according the size of the cache?

**Comment by erez-speedb** [comment]
@udi-speedb  single value.
The comment is for future auto-tuning.

**Comment by hilikspdb** [comment]
I suggest we will stick to a simple value at first (10%) in the current version. The results are much better than cache_index_.. = true. 

 I think that  in the next version we should set  both sizes based on the cache size. 
1.  mid value = (cache size - (write buffer size * compaction trigger)) / cache size 
2. bottom value =   (cache size - 10*(write buffer size * compaction trigger)) / cache size
but these setting require testings that i am not sure we have ....
