### ISSUE TITLE
db_test assertion - changing dynamically write buffer size not aligned with pending memtable creation

### ISSUE THREAD

**Issue by ayulas** [speedb-io/speedb#69]
in db test changing dynamically write buffer size and it is not aligned to the fact we have an active memtable and a pending memtable...
so the check of the L0 files (meainng the memtable that have done flush) depending the increase/decrease write buffer size is incorrect cause the pending memtable is created with the previous write buffer size ...

**Comment by isaac-io** [comment]
Irrelevant since #25 was reverted.
