### ISSUE TITLE
unit tests: some tests are stuck

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/speedb#697]
It seems like the changes done in #656 are responsible for some of the unit tests to hang during CI. 
It also seems to be timing dependent since this does not happen every time and it doesnt happen locally or on GCP instances.
here are 3 tests which were stuck during a recent manual CI run on main ( fc2bee8)  - https://github.com/speedb-io/speedb/actions/runs/6335075486 :
DBCompactionTestWithParamWithMCC/DBCompactionTestWithParamWithMCC.CancelCompactionWaitingOnConflict/1
DBCompactionTestWithParamWithMCC/DBCompactionTestWithParamWithMCC.CancelCompactionWaitingOnConflict/3
DBCompactionTestWithParamWithMCC/DBCompactionTestWithParamWithMCC.CancelCompactionWaitingOnConflict/6

I've also seen DBCompactionTestWithMCC/DBCompactionTestWithMCC.CompactionLimiter/1 fail on occasion

**Comment by Yuval-Ariel** [comment]
we'll temporarily disable these tests so that CI on main doesnt fail and i'll open a new ticket to fix and re enable them.

**Comment by udi-speedb** [comment]
I have added #714 to investigate and actually fix in the future
