### ISSUE TITLE
support enable speedb feature in CI

### ISSUE THREAD

**Issue by ayulas** [speedb-io/speedb#723]
support enable speedb feature in CI

**Comment by Guyme** [comment]
fixes  : #726

**Comment by Guyme** [comment]
@Guyme will talk to @RoyBenMoshe and see where we take it from there

**Comment by ayulas** [comment]
@Guyme i talked with @RoyBenMoshe on Friday 
What he explained is that the design wasn’t supposed to support recover shared option
To be able support db stress we need some adjustments to it 
Any way decide what you want to do

**Comment by hilikspdb** [comment]
The idea is that the user should call enable_sp.. before any open of the database (new or existing) . all the options that are set are mutable options and the user may change the parameters between runs and use different setting. Rocksdb lacks a config file that is shared between databases and while is see the value i do not think we should tie this project to it.

**Comment by Guyme** [comment]
to my understanding - to close this correctly we need to make sure that dbstress calls on enable_speedb in recovery

**Comment by Guyme** [comment]
@ayulas - #742 is now merged.
Please fix the CI to use enable speedb in recovery as well

**Comment by ayulas** [comment]
Ok

**Comment by ayulas** [comment]
@ofriedma pls approve
