### ISSUE TITLE
isuue with enable speedb features 

### ISSUE THREAD

**Issue by erez-speedb** [speedb-io/speedb#729]
Testing current main.
Running with 
`db_bench --compression_type=None -db=/data/ -num=1000000000 -value_size=100 -key_size=16 -report_interval_seconds=1 -stats_dump_period_sec=120 -num_column_families=1 -write_buffer_size=268435456 -histogram -statistics -stats_dump_period_sec=60 -confidence_interval_only -benchmark_read_rate_limit=0 -benchmark_write_rate_limit=0 -report_file=fillrandom.csv --disable_wal=true --benchmarks=fillrandom,levelstats,memstats --enable_speedb_features=true -total_ram_size=3221225472 -max_background_jobs=12 -delayed_write_rate=536870912`
End with 
`ERROR: --pinning_policy should not be set when --unpartitioned_pinning is set.`

**Comment by udi-speedb** [comment]
@erez-speedb - Please try the branch 729-isuue-with-enable-speedb-features

**Comment by erez-speedb** [comment]
@udi-speedb  branch 729-isuue-with-enable-speedb-features works fine,
