### ISSUE TITLE
db_bench: Sync applicable db_bench's properties with enable speedb features

### ISSUE THREAD

**Issue by udi-speedb** [speedb-io/speedb#743]
When activating  enable speedb features in db_bench, we are creating and overriding Options' properties.
db_bench has its own. 
For example, db_bench has its own cache handling that seems not to be fully synchronised with the SharedOptions's own cache entity:

1. no_block_cache is set according to the db_bench's cache_ member.
2. db_bench creates a SimCache as its cache if simcache_size >= 0.

We should review all the overrides that enables speedb features does and make sure they are fully synchronized with db_bench.

**Comment by ofriedma** [comment]
https://github.com/speedb-io/speedb/pull/765

**Comment by ofriedma** [comment]
@erez-speedb moved to performance in order to check if it doesn't fail for the performance tests, it doesn't affect the performance of the tool or the db itself.

**Comment by erez-speedb** [comment]
Passed perf test on hash 06fcbd35
