### ISSUE TITLE
ZLIB 1.3: Complete the update of the url-s in Makefile / CMakeLists.txt

### ISSUE THREAD

**Issue by udi-speedb** [speedb-io/speedb#824]
As part of #820, the ci files were updated to reference zlib 1.3 on GitHub. However, the Makefile / CMakeLists.txt still use the old, unusable zlib 1.3. url-s. 
These files need to be updated as well.

**Comment by Yuval-Ariel** [comment]
addressing this in #820

**Comment by udi-speedb** [comment]
> addressing this in #820

Please just finish it now. Chaning the CI and Makefile and leaving cmake out really doesn't make sense.

**Comment by ofriedma** [comment]
CMakeLists.txt does not need to change.
cmake does not build zlib, it just use an installed already library of zlib
