### ISSUE TITLE
2.8.0 release speedbjni JAR is not available in maven repositories

### ISSUE THREAD

**Issue by dparrella** [speedb-io/speedb#829]
**Describe the bug**
The 2.8.0 release JAR is not available in maven repositories.

**To Reproduce**
1.  Update version for speedbjni dependency in POM from 2.7.0 -> 2.8.0
2. Run mvn clean install
3. Observe build failure because artifact cannot be found in maven repositories.

**Expected behavior**
Build should succeed with version 2.8.0.

Build should be present in maven repositories: https://mvnrepository.com/artifact/io.github.speedb-io/speedbjni

**System (please complete the following information):**
 - OS: MacOS
 - Hardware [e.g. Intel Xeon Ice Lake, 64GB, NVMe]

**Additional context**

Output from maven build:
```
[ERROR] Failed to execute goal on project *****: Could not resolve dependencies for project ****:jar:2.0.0-SNAPSHOT: The following artifacts could not be resolved: io.github.speedb-io:speedbjni:jar:2.8.0 (absent): Could not find artifact io.github.speedb-io:speedbjni:jar:2.8.0 in maven-central 
```

**Comment by maxb-io** [comment]
Hello @dparrella the 2.8.0 JAR is now available on the Maven Central
https://central.sonatype.com/artifact/io.github.speedb-io/speedbjni

Hope this helps.

**Comment by dparrella** [comment]
Thank you, @maxb-io !
