### ISSUE TITLE
Decrease the default bucket number in hash_spd to 400,000 

### ISSUE THREAD

**Issue by erez-speedb** [speedb-io/speedb#854]
The current consume too much memory and test with 1,000,000,000 small obj in 4 CF showed little to none degraded performance with 400k

**Comment by Guyme** [comment]
@ayulas - Please review Erez's findings and if you are in agreement please make the change.
Thanks

**Comment by ayulas** [comment]
Agree change will be made

**Comment by ayulas** [comment]
done https://github.com/speedb-io/speedb/pull/856
